# Generated by Django 6.0.2 on 2026-03-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_insumo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
