# Generated by Django 6.0.5 on 2026-05-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_usuario_password_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'ADMINISTRADOR'), ('Empleado', 'EMPLEADO'), ('Cliente', 'CLIENTE')], default='Cliente', max_length=15),
        ),
    ]
