# Generated by Django 6.0.5 on 2026-06-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_delete_insumo_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Camisetas', 'CAMISETAS'), ('Pantalones', 'PANTALONES'), ('Chaquetas', 'CHAQUETAS'), ('Accesorios', 'ACCESORIOS'), ('Insumos', 'INSUMOS'), ('Otros', 'OTROS')], max_length=50),
        ),
    ]
