# Generated by Django 6.1 on 2026-08-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_compra_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(blank=True, default='', max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=300)),
                ('orden', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='configuracion/')),
                ('orden', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='INTSHOT', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/')),
                ('hero_titulo', models.CharField(default='Optimiza la gestión de tu inventario y pedidos con INTSHOT', max_length=200)),
                ('hero_texto', models.CharField(default='Un sistema diseñado especialmente para empresas textiles que buscan controlar insumos, productos terminados y pedidos de manera eficiente.', max_length=500)),
                ('hero_imagen', models.ImageField(blank=True, null=True, upload_to='configuracion/')),
                ('titulo_catalogo', models.CharField(default='Nuestro catálogo', max_length=100)),
                ('titulo_caracteristicas', models.CharField(default='Características', max_length=100)),
                ('titulo_beneficios', models.CharField(default='¿Por qué elegir INTSHOT?', max_length=100)),
                ('texto_footer', models.CharField(blank=True, default='INTSHOT - Sistema de gestión de inventario', max_length=300)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vineta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
            ],
        ),
    ]
