# Generated by Django 6.1 on 2026-08-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_beneficio_caracteristica_configuracion_vineta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='texto_footer',
            field=models.CharField(blank=True, default='Todos los derechos reservados', max_length=300),
        ),
    ]
