# Generated by Django 6.1 on 2026-09-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_detallecompra_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='limite_stock_bajo',
            field=models.IntegerField(default=10),
        ),
    ]
