# Generated by Django 6.0.5 on 2026-06-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
