# Generated by Django 6.0.2 on 2026-06-12 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_carrito_compra_detallecompra_movimientoinventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='cantidad_recibida',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'PENDIENTE'), ('Recibida', 'RECIBIDA'), ('Recibida parcialmente', 'RECIBIDA PARCIALMENTE')], default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'PENDIENTE'), ('En proceso', 'EN PROCESO'), ('Enviado', 'ENVIADO'), ('Entregado', 'ENTREGADO'), ('Cancelado', 'CANCELADO')], default='Pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Ingreso', 'INGRESO'), ('Egreso', 'EGRESO')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=300)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.compra')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.pedido')),
            ],
        ),
    ]
